trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: TerraformVariables
- name: http_proxy
  value: 'http://proxyusername:proxypassword@proxyaddress:proxyport'
- name: https_proxy
  value: 'https://proxyusername:proxypassword@proxyaddress:proxyport'

steps:
- script: |
    git config --global http.proxy $(http_proxy)
    git config --global https.proxy $(https_proxy)
  displayName: 'Configure Git Proxy'

- task: UseTerraform@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: $(serviceConnectionName)
  displayName: 'Terraform Init for Main Infra'

- task: UseTerraform@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: $(serviceConnectionName)
    additionalArgs: '-var "location=$(location)" -var "resource_group_name=$(resourceGroupName)"'
  displayName: 'Terraform Plan for Main Infra'

- task: UseTerraform@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceName: $(serviceConnectionName)
    additionalArgs: '-auto-approve -var "location=$(location)" -var "resource_group_name=$(resourceGroupName)"'
  displayName: 'Terraform Apply for Main Infra'
